services:
  postgres:
    image: postgres:16
    container_name: app-postgres-local
    environment:
      POSTGRES_DB: app_local
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
