spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none         # we let Flyway manage schema
    properties:
      hibernate.format_sql: true
      hibernate.jdbc.time_zone: UTC
  flyway:
    enabled: true

#---
#spring:
#  config:
#    activate:
#      on-profile: local
#  datasource:
#    url: jdbc:postgresql://localhost:5432/app_local
#    username: local
#    password: local
#  jpa:
#    hibernate.ddl-auto: create-drop   # only for early laptop dev
## run with: SPRING_PROFILES_ACTIVE=local

---
spring:
  config:
    activate:
      on-profile: develop
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate.ddl-auto: validate

#---
#spring:
#  config:
#    activate:
#      on-profile: testing
#  datasource:
#    url: ${DATABASE_URL}
#    username: ${DATABASE_USERNAME}
#    password: ${DATABASE_PASSWORD}
#  jpa:
#    hibernate.ddl-auto: validate
#
#---
#spring:
#  config:
#    activate:
#      on-profile: prod
#  datasource:
#    url: ${DATABASE_URL}
#    username: ${DATABASE_USERNAME}
#    password: ${DATABASE_PASSWORD}
#  jpa:
#    hibernate.ddl-auto: validate
