spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate.format_sql: true
      hibernate.jdbc.time_zone: UTC
    defer-datasource-initialization: true
  sql:
    init:
      mode: never
  flyway:
    enabled: false   # <— IMPORTANT: off by default

---
spring:
  config:
    activate:
      on-profile: develop
  datasource:
    url: ${DATABASE_URL}          # jdbc:postgresql://host:port/db
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    url: ${DATABASE_URL}
    user: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    # baseline-on-migrate: true   # uncomment if DB already has tables
