spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/app_local
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update            # local iteration only
    properties:
      hibernate.format_sql: true
    defer-datasource-initialization: true

  flyway:
    enabled: false                # local uses Hibernate, not Flyway

  sql:
    init:
      mode: never                 # no schema.sql/data.sql
